### ISSUE TITLE
Error in new version

### ISSUE THREAD

**Issue by infuse89** [Kitware/visualizer#15]
on v2.0.18 i have error when start visualizer

```
ls: no such file or directory: /Applications
ls: no such file or directory: /usr/local/opt/

===============================================================================
| Execute:
| $ "/home/k1ng/Downloads/ParaView-5.2.0-Qt4-OpenGL2-MPI-Linux-64bit/bin/pvpython"
|	-dr
|	"/usr/local/lib/node_modules/pvw-visualizer/server/pvw-visualizer.py"
|	--content
|	"/usr/local/lib/node_modules/pvw-visualizer/dist"
|	--port
|	8080
|	--data
|	"/home/k1ng/parav/data/granata/files"
===============================================================================

2017-02-10 10:43:21+0200 [-] Log opened.
2017-02-10 10:43:21+0200 [-] Traceback (most recent call last):
2017-02-10 10:43:21+0200 [-]   File "/usr/local/lib/node_modules/pvw-visualizer/server/pvw-visualizer.py", line 219, in <module>
2017-02-10 10:43:21+0200 [-]     server.start_webserver(options=args, protocol=_VisualizerServer)
2017-02-10 10:43:21+0200 [-]   File "/home/k1ng/Downloads/ParaView-5.2.0-Qt4-OpenGL2-MPI-Linux-64bit/lib/python2.7/site-packages/vtk/web/server.py", line 185, in start_webserver
2017-02-10 10:43:21+0200 [-]     appSession = protocol(types.ComponentConfig(realm = "vtkweb"))
2017-02-10 10:43:21+0200 [-]   File "/home/k1ng/Downloads/ParaView-5.2.0-Qt4-OpenGL2-MPI-Linux-64bit/lib/python2.7/site-packages/paraview/web/wamp.py", line 13, in __init__
2017-02-10 10:43:21+0200 [-]     wamp.ServerProtocol.__init__(self, config)
2017-02-10 10:43:21+0200 [-]   File "/home/k1ng/Downloads/ParaView-5.2.0-Qt4-OpenGL2-MPI-Linux-64bit/lib/python2.7/site-packages/vtk/web/wamp.py", line 62, in __init__
2017-02-10 10:43:21+0200 [-]     self.initialize()
2017-02-10 10:43:21+0200 [-]   File "/usr/local/lib/node_modules/pvw-visualizer/server/pvw-visualizer.py", line 183, in initialize
2017-02-10 10:43:21+0200 [-]     self.registerVtkWebProtocol(pv_protocols.ParaViewWebViewPort(_VisualizerServer.viewportScale, _VisualizerServer.viewportMaxWidth, _VisualizerServer.viewportMaxHeight))
2017-02-10 10:43:21+0200 [-] TypeError: __init__() takes exactly 1 argument (4 given)
```

on version 2.0.16 all work fine, what i do wrong?

command to start 

`Visualizer -d /home/k1ng/parav/data/granata/files --paraview /home/k1ng/Downloads/ParaView-5.2.0-Qt4-OpenGL2-MPI-Linux-64bit/`

**Comment by jourdain** [comment]
I've added a new feature in ParaView/master and updated Visualizer so additional options could be provided.

```
--viewport [1x2560x1440]        Configure viewport {scale}x{maxWidth}x{maxHeight}
```

ParaView 5.2 will only work with Visualizer up to 2.0.17.

But you can easily patch your downloaded ParaView to work with the latest Visualizer by replacing your file `/home/k1ng/Downloads/ParaView-5.2.0-Qt4-OpenGL2-MPI-Linux-64bit/lib/python2.7/site-packages/paraview/web/protocols.py` by the file available [here](https://raw.githubusercontent.com/Kitware/ParaView/master/Web/Python/paraview/web/protocols.py)

**Comment by infuse89** [comment]
It works, thanks

**Comment by auxiliary** [comment]
The link to the provided patch is broken.

**Comment by jourdain** [comment]
https://raw.githubusercontent.com/Kitware/ParaView/master/Web/Python2/paraview/web/protocols.py
