### ISSUE TITLE
:CRITICAL:twisted:Unhandled Error

### ISSUE THREAD

**Issue by Shaileshbg1** [Kitware/visualizer#78]
Hi Jourdain,

As per your suggestion, I was able to install pvw-visualizer from npm.. I could not install wslink inside my docker (it kept saying requirements.txt  not found despite my repeated efforts.) So I installed wslink outside and copied the contents onto my container and fed all the paths correctly. But when I run it I get the following error:
`CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "/postProcess_app/paraview/build/lib/python3.5/site-packages/twisted/web/http.py", line 1588, in dataReceived
    finishCallback(data[contentLength:])
  File "/postProcess_app/paraview/build/lib/python3.5/site-packages/twisted/web/http.py", line 1980, in _finishRequestBody
    self.allContentReceived()
  File "/postProcess_app/paraview/build/lib/python3.5/site-packages/twisted/web/http.py", line 2059, in allContentReceived
    req.requestReceived(command, path, version)
  File "/postProcess_app/paraview/build/lib/python3.5/site-packages/twisted/web/http.py", line 869, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/postProcess_app/paraview/build/lib/python3.5/site-packages/twisted/web/server.py", line 184, in process
    self.render(resrc)
  File "/postProcess_app/paraview/build/lib/python3.5/site-packages/twisted/web/server.py", line 235, in render
    body = resrc.render(self)
  File "/postProcess_app/paraview/build/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/postProcess_app/paraview/build/lib/python3.5/site-packages/wslink/launcher.py", line 496, in render_POST
    payload = json.loads(request.content.getvalue())
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
builtins.TypeError: the JSON object must be str, not 'bytes'
`

Could you please look into it and let me know on how to proceed. Any suggestion would be greatly appreciated.

Regards,
Shailesh

**Comment by jourdain** [comment]
Please provide an explanation of how you built your docker image along with what you are doing.
It is kind of impossible to help you without understanding some context of what you are trying to do.

**Comment by Shaileshbg1** [comment]
Thank you very much for your quick response.. that issue turned out to be a python 3.5 utf8 encoding issue, and it was solved by adding the encoding to JSON.load line in launcher.py, I still am not getting visualizer working, I will do my homework and get back to you with the complete logs and details. Thank you again for your time

**Comment by jourdain** [comment]
FYI @aronhelser, so you can fix wslink to fully support Python 3.

**Comment by Shaileshbg1** [comment]
Hello Jourdain,

I was able to get the Visualizer working, but it takes a lot of time to get a response for any action I do with it (like rotation, zoom, pan, etc.) It takes a lot of time to generate the blob and to visualize it, but my main requirement is quick interactive visualization. 

Generating webgl from ParaView and visualizing it has always been very fast because everything is on the client side. But I need the workflow panel and filters of Visualizer. Is there a way in which I can combine the two? Get the speed of webgl and the utility of Visualizer? Or is there a way in which I can speed up the interactive visualization process on Visualizer. I am using a single PWServer and not a cluster, I am working on a micro instance of AWS, I am using google chrome as my browser, but I tried with other browsers but with not much improvement. The model which I am visualizing is also not big, it has only 6 lakh face centers. Any suggestion would be greatly appreciated.

Regards,
Shailesh

**Comment by scottwittenburg** [comment]
@Shaileshbg1 have you tried local rendering in Visualizer?  Click on the cogs icon in the panel on the left, then uncheck the "Remote Rendering" checkbox.  The geometry will be transferred to your browser and rendered locally with vtk.js.

**Comment by Shaileshbg1** [comment]
Hello, 

Thank you very much for your reply. When I uncheck remote rendering, I lose my rendered image and I get a blank screen. 

![checked](https://user-images.githubusercontent.com/32194415/59035067-14f55e80-888a-11e9-9a9d-885cde43f013.png)

![unchecked](https://user-images.githubusercontent.com/32194415/59035121-33f3f080-888a-11e9-85d2-de588783e730.png)


This is what I have done to build ParaView5.5.2 on python3.5:
1) Built ParaView using the repo, built all the dependencies (MPI, ffmpeg)
2) Built Osmesa manually, with llvm and mesa 18
3) Built Visualizer manually with npm bundle and wslink

Any suggestion would be greatly appreciated.

Regards,
Shailesh

**Comment by scottwittenburg** [comment]
Is there any error output in the console you could share?

**Comment by Shaileshbg1** [comment]
This is the console error output:

Failed to add observer to view 4017
Visualizer.js:6 {code: -32001, data: {…}, message: "Exception raised"}
Visualizer.js:1 
          Can not forward events without a current renderer on the interactor.

**Comment by Shaileshbg1** [comment]
Hello Scott,

I am still getting the same exception when I uncheck the "Remote Rendering" checkbox. Please let me know if any further information is required from my end. Any suggestion would be greatly appreciated.

Regards,
Shailesh

**Comment by scottwittenburg** [comment]
The error messages in your browser may contain a python stack trace from the server side if you drill down into them.  Can you see if that's true, and if so, paste that stack trace here?  Or if you can capture the log information generated by the pvpython process on the server side, that could help too.

Is there a specific reason why you built ParaView 5.5.2 instead of 5.6.0?

**Comment by Shaileshbg1** [comment]
Hello,

Reason for choosing ParaView 5.5.2 over 5.6.0 is that when we built it using 5.6.0 it had many files missing. I had raised the issue on ParaView discourse here:
https://discourse.paraview.org/t/error-cannot-import-vtkpvanimation-while-building-paraview-with-python-3/1797/7
It did say it was merged with master, but when we tried it still had a lot of files missing. So I went with the next stable version of 5.5.2

![before](https://user-images.githubusercontent.com/32194415/59433849-f7834000-8e07-11e9-8621-682464ef601f.png)
As you can see there is no change when the remote rendering check box is checked off. And I could not find any python stack trace from the server side.
![after](https://user-images.githubusercontent.com/32194415/59433897-0e299700-8e08-11e9-84d3-08a7802ce01f.png)

The only trace I could find was with /paraview 
![paraview](https://user-images.githubusercontent.com/32194415/59434052-66f92f80-8e08-11e9-96f7-31313a5e6d5b.png)

We did try to capture the log from pvpython process but that too did not give any error messages.

Any suggestion would be greatly appreciated.

**Comment by jourdain** [comment]
The error seems related to the launcher. When you run, visualizer by hand, do you see any error?

**Comment by jourdain** [comment]
BTW, I do remember something about some WebGL issue in 5.5 that we fixed in 5.6.
