### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by sptrotter** [Kitware/visualizer#8]
I followed the instructions in the Readme on how to build with npm, however when the build runs it gets an error on the "fix-autobahn && webpack" step. I get the same error when trying to build ParaviewWeb. The error is below:

> pvw-visualizer@0.0.0-semantically-release build C:\visualizer\visualizer
> fix-autobahn && webpack

path.js:146
      throw new TypeError('Arguments to path.resolve must be strings');
            ^
TypeError: Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at Object.<anonymous> (C:\visualizer\visualizer\node_modules\paraviewweb\tools\fix-autobahn\patch-autobahn-0.9.6-cli.js:10:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.2
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! pvw-visualizer@0.0.0-semantically-release build: `fix-autobahn && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pvw-visualizer@0.0.0-semantically-release build script 'fix-autobahn && webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pvw-visualizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     fix-autobahn && webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pvw-visualizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pvw-visualizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\visualizer\visualizer\npm-debug.log

**Comment by jourdain** [comment]
Thanks for reporting back. We haven't try the repo on Windows hence the issue you are facing although, nothing should stop the Web client from being built on Windows. 
Will look into it. Although do you mind trying with a newer version of Node? (4 or 5)

**Comment by sptrotter** [comment]
Hi Sebastien,

I upgraded Node to 5.10.1, however I still get the same issue. FYI, I’m building on Windows 10 x64.

Thanks,
Stuart

**Comment by jourdain** [comment]
Thanks Stuart,

Will try to find a Windows machine here and see what I can find...

**Comment by tldv** [comment]
Here's another data point, also on Win 10 Node v5.10.1, this time the error lies in fix-kw-web-suite. Double checking the install folder indicates this install finished incomplete.


[npm-debug.txt](https://github.com/Kitware/visualizer/files/217964/npm-debug.txt)
'fix-kw-web-suite' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "pvw-visualizer"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! pvw-visualizer@1.0.11 postinstall: `fix-kw-web-suite || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pvw-visualizer@1.0.11 postinstall script 'fix-kw-web-suite || true'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pvw-visualizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     fix-kw-web-suite || true
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pvw-visualizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pvw-visualizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by tldv** [comment]
Nevermind, installing kw-web-suite fixes my problem. Visualizer is now installed on my Win 10 machine.

**Comment by jourdain** [comment]
Thanks for the update although you should not need to install it globally. Even if that doesn't hurt...

This postinstall script is only needed for old npm... Maybe I'll remove it and force users to have npm 3+.

**Comment by jourdain** [comment]
http://kitware.github.io/paraviewweb/docs/guides/ami.html

**Comment by tldv** [comment]
Thanks! I couldn't find the other two, but the US East image worked for me.
